### PR TITLE
holistic

### PR DESCRIPTION
**Pull request by untzag**
function derived from TOPAS preamp tuning

### CODE REVIEW

**Comment by ksunden** [comment]
This pull request **introduces 3 alerts** when merging 8c5e4633c91a3c861341330b34f03c1c06caaed0 into 56a85f9664d75213858ecec9ce57ff70797a9662 - [view on LGTM.com](https://lgtm.com/projects/g/wright-group/attune/rev/pr-429802b501a2e7f7559f9957f619cac1fc5ebe7f)

**new alerts:**

* 1 for Constant in conditional expression or statement
* 1 for Unused import
* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ksunden** [comment]
This pull request **introduces 5 alerts** when merging 40148e832302113a03f95e515d54237e2b5c86e5 into 56a85f9664d75213858ecec9ce57ff70797a9662 - [view on LGTM.com](https://lgtm.com/projects/g/wright-group/attune/rev/pr-379fcba2283b08bc2f7f30827b87c5e288fb84e7)

**new alerts:**

* 2 for Unused local variable
* 1 for Mismatch in multiple assignment
* 1 for Constant in conditional expression or statement
* 1 for Unreachable code

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ksunden** [comment]
Data file updated using wright-group/WrightTools#909. Simply called from_PyCMDS and save, no stripping of variables (only one channel to begin with)

**Comment by ksunden** [comment]
I did some blackening in here... Probably should have held off, luckily only one other PR is open

**Comment by ksunden** [comment]
Tests are failing due to wright-group/WrightTools#923 not being in the released version, tests pass on current master WT (at least locally)

**Comment by ksunden** [comment]
@darienmorrow Have you had a chance to see if this is usable/makes sense?

**Comment by darienmorrow** [comment]
@ksunden I have briefly perused the PR and used holistic on my OSX machine. 

I think we should merge this PR.

**Pull request merged**
