### PR TITLE
Update _discrete_tune.py

### LINKED ISSUE #156: DiscreteTune: `__call__` fails for array argument
The core issue is that logic checking range expects a numeric argument:
https://github.com/wright-group/attune/blob/e9a4937b6fda24dfd10baf2fc674c15542861aba/attune/_discrete_tune.py#L41

Don't have exact traceback on hand, but this comes up in practice because of plotting in workup routines, which uses `instrument.__call__` (only for plotting purposes):

https://github.com/wright-group/attune/blob/e9a4937b6fda24dfd10baf2fc674c15542861aba/attune/_plot.py#L36

### PR DESCRIPTION
**Pull request by ddkohler**
Allow call(v) to work when v is an array type.

Resolves #156

### CODE REVIEW

**Comment by ksunden** [comment]
I think this should rather return an ndarray with the value for every entry. thoughts?

**Comment by ddkohler** [comment]
I agree with you @ksunden .  It gives the most consistency with the Tune class. 

I've implemented the change and am waiting for testing on Waldo.

**Comment by ksunden** [comment]
@ddkohler status?

**Comment by ddkohler** [comment]
still needs to be tested on Waldo.  I'll try to get someone to use it soon...

**Pull request merged**
